### ISSUE TITLE
custom widget for qt5.5

### ISSUE THREAD

**Issue by khmaies5** [chrisaverage/burger-menu#1]
i couldn't make a custom widget from this code can you help me?

**Comment by chrisaverage** [comment]
What do you mean by that?

**Comment by khmaies5** [comment]
i want to make this burger menu available in qt creator widget box by creating a custom designer widget in qt creator

**Comment by chrisaverage** [comment]
That's cool, but you're reporting an issue. What's the issue?

**Comment by khmaies5** [comment]
I am reporting an issue because i didn't find other way speak with you. I need your help to make this widget usable in qt deaigner

**Comment by chrisaverage** [comment]
I've added a designer plugin project. The properties can be set from the designer, but I see no API to integrate it with the built-in action editor, so the actions need to be added from code.

**Comment by khmaies5** [comment]
i will try it and tell you the result
